### ISSUE TITLE
TS2304: Cannot find name 'bool'.

### ISSUE THREAD

**Issue by sparkbuzz** [PureMVC/puremvc-typescript-standard-framework#1]
I'm getting errors in **puremvc-typescript-standard-1.0.d.ts** when compiling:

*Error:(13, 41) TS2304: Cannot find name 'bool'.*

http://www.typescriptlang.org/Handbook#basic-types-boolean

Should the types perhaps be converted to boolean? If so, I can make the change and do PR.

**Comment by cliffhall** [comment]
Thanks Josef, if you could PR that would be great.

Cheers,
-=Cliff>

**Comment by sparkbuzz** [comment]
PR created: https://github.com/PureMVC/puremvc-typescript-standard-framework/pull/2

**Comment by cliffhall** [comment]
Thank you, sir.
